services:
  backend_api:
    image: ngaleuj/backend_api:latest
    ports:
      - 5005:5005
    build:
      context: backend/
    depends_on:
      - db_postgres
    environment:
      - ENV=docker
    env_file:
      - /backend/.env.docker
    restart: always
    
  frontend:
    image: ngaleuj/frontend:latest
    ports:
      - 5000:5000
    build:
      context: frontend/
    depends_on:
      - backend_api
    environment:
      - ENV=docker
    env_file:
      - /frontend/.env
    restart: always
    

  db_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
